dependencies:
  - name: newrelic-infrastructure-v3
    alias: newrelic-infrastructure
    repository: file://../newrelic-infrastructure-v3
    condition: infrastructure.enabled
    version: 3.0.21

  - name: nri-prometheus
    repository: file://../nri-prometheus
    condition: prometheus.enabled
    version: 1.13.2

  - name: nri-metadata-injection
    repository: file://../nri-metadata-injection
    condition: webhook.enabled
    version: 2.2.0

  - name: newrelic-k8s-metrics-adapter
    repository: file://../newrelic-k8s-metrics-adapter
    condition: metrics-adapter.enabled
    version: 0.3.1

  - name: kube-state-metrics
    repository: https://kubernetes.github.io/kube-state-metrics
    condition: ksm.enabled
    version: 2.13.2

  - name: nri-kube-events
    repository: file://../nri-kube-events
    condition: kubeEvents.enabled
    version: 1.13.0

  - name: newrelic-logging
    repository: file://../newrelic-logging
    condition: logging.enabled
    version: 1.10.9

  - name: newrelic-pixie
    repository: file://../newrelic-pixie
    condition: newrelic-pixie.enabled
    version: 1.5.0

  - name: pixie-operator-helm2-chart
    alias: pixie-chart
    repository: https://pixie-operator-charts.storage.googleapis.com
    condition: pixie-chart.enabled
    version: 0.0.18

  - name: newrelic-infra-operator
    repository: file://../newrelic-infra-operator
    condition: newrelic-infra-operator.enabled
    version: 0.4.0
